name: CI - Enhanced Memusage Testing on openSUSE Leap 15.6

on:
  push:
    branches:
      - main
    paths:
      - 'memusage.py'
      - 'INSTALL.md'
  pull_request:
    branches:
      - main
    paths:
      - 'memusage.py'
      - 'INSTALL.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests in openSUSE Leap 15.6 container
      run: |
        # Pull and run openSUSE container
        docker run -d --name test-opensuse -v $(pwd):/workspace -w /workspace opensuse/leap:15.6 zypper refresh
        docker exec test-opensuse zypper install -y python3 python3-pip python3-devel gcc stress-ng
        docker exec test-opensuse pip3 install --user psutil
        docker exec test-opensuse python3 -c "import sys; sys.path.append('/root/.local/lib/python3.6/site-packages'); import psutil; print('psutil imported successfully!')"

        # Test help without sudo
        docker exec test-opensuse python3 memusage.py --help
        echo "Help command executed!"

        # Simulate processes with stress-ng and test output
        docker exec test-opensuse stress-ng --vm 2 --vm-bytes 50M --vm-keep -t 10s &
        sleep 5
        docker exec test-opensuse python3 memusage.py | grep -i "memory"  # Check for memory output
        [ $? -eq 0 ] && echo "Memory usage detected in output!"

        # Cleanup
        docker exec test-opensuse pkill -f stress-ng
        docker stop test-opensuse
        docker rm test-opensuse
        echo "Test completed!"
