name: Clean workflows

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  actions: write

jobs:
  limpar:
    runs-on: ubuntu-latest
    steps:
      - name: clean workflows with erros
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;

            async function deleteWorkflowRunsByStatus(status) {
              const runs = await github.rest.actions.listWorkflowRunsForRepo({
                owner,
                repo,
                status: status,
              });
              for (const run of runs.data.workflow_runs) {
                await github.rest.actions.deleteWorkflowRun({
                  owner,
                  repo,
                  run_id: run.id,
                });
              }
            }

            await deleteWorkflowRunsByStatus('failure');

            await deleteWorkflowRunsByStatus('cancelled');

            await deleteWorkflowRunsByStatus('timed_out');
