name: Clean workflows

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: read
  actions: write
  workflows: write

jobs:
  limpar:
    runs-on: ubuntu-latest
    steps:
      - name: Limpar workflows com falhas
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner,
              repo,
              status: 'failure',
            });
            for (const run of runs.data.workflow_runs) {
              await github.rest.actions.deleteWorkflowRun({
                owner,
                repo,
                run_id: run.id,
              });
            }
