name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: opensuse/leap:15.6
    strategy:
      matrix:
        python-version: ["3.6", "3.9"]
    steps:
    - name: Clear GitHub Actions cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Set up Git
      uses: actions/setup-git@v3
      with:
        git-version: '2.39.2'
    - name: Download and extract code  # Download manual com wget e tar
      run: |
        wget https://github.com/mariosergiosl/memusage/archive/refs/heads/main.tar.gz
        tar -xzf main.tar.gz
    - name: Install dependencies
      run: |
        zypper ref
        zypper in -y tar
        zypper in -y pylint
    - name: Add tar to PATH 
      run: echo "PATH=$PATH:/usr/bin" >> $GITHUB_ENV
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc $(git ls-files '*.py')
    - name: Run pytest
      run: |
        pip install pytest
        python -m pip install .
        pytest -v tests/
