name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    container: opensuse/leap:15.6  # Usando o openSUSE Leap 15.6
    steps:
    - uses: actions/checkout@v3
    - name: Install pylint
      run: |
        zypper ref
        zypper in -y pylint
    - name: Run pylint
      run: |
        pylint --rcfile=.pylintrc $(git ls-files '*.py')
