name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint with pylint
      uses: docker://opensuse/tumbleweed:latest
      with:
        entrypoint: /bin/bash
        args: |
          rpm -Uvh http://download.opensuse.org/tumbleweed/repo/oss/x86_64/zypper-1.14.51-1.1.x86_64.rpm
          zypper ref
          zypper in -y tar
          zypper in -y pylint
          pylint --rcfile=.pylintrc $(git ls-files '*.py')
