name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Setup openSUSE
      uses: jirutka/setup-opensuse@v1
      with:
        version: '15.6'
    - name: Set up Git
      uses: actions/setup-git@v3
      with:
        git-version: '2.39.2'
    - name: Add tar to PATH 
      run: echo "PATH=$PATH:/usr/bin" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Lint with pylint
      run: |
        zypper ref
        zypper in -y pylint
        pylint --rcfile=.pylintrc $(git ls-files '*.py')
