name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint with pylint
      uses: docker://opensuse/leap:15.6
      with:
        entrypoint: /bin/bash
        args: |
          zypper ref
          zypper in -y tar
          zypper in -y pylint
          pylint --rcfile=.pylintrc $(git ls-files '*.py')
