name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint with pylint
      uses: docker://opensuse/leap:15.6
      with:
        entrypoint: /bin/bash
        args: |
          /usr/bin/rpm -Uvh http://download.opensuse.org/tumbleweed/repo/oss/x86_64/zypper-1.14.51-1.1.x86_64.rpm
          /usr/bin/zypper ref
          /usr/bin/zypper in -y pylint
          /usr/bin/pylint --rcfile=.pylintrc $(/usr/bin/git ls-files '*.py')
